### ISSUE TITLE
Shopping Sites Stock Monitoring

### ISSUE THREAD

**Issue by oaykut** [max99x/pagemon-chrome-ext#344]
Hi,

I have just started to use your page monitor plugin.

Below there are 4 different shopping sites for a football shirt and I wrote the available sizes for this shirt.

http://www.barcin.com/adidas-besiktas-2014-2015-sezonu-deplasman-forma-b21492
Size = XS - S

http://www.koraysporfutbol.com/adidas-futbol-giyim-kulup-takimlari-bjk-14-away-ss-b21492
Size = XS - S - M - L - XL

https://www.yalispor.com.tr/adidas-bjk-14-away-ss
Size = XS - S - XL - XXL

http://www.morhipo.com/adidas-forma-besiktas/13701520/detay
Size = S - M - L - XL - XXL

What I want to do it is to check the available sizes every day and to be informed if any size is added or become out of stock.

I am not interested in any other changes in these sale pages, just the sizes. Can I achieve it with your application?

These 4 sites are just for learning. There will be more shirts and websites if I am able to do it.

Best regards,
Baris

**Comment by max99x** [comment]
Most of those generate the choices dynamically on the client using JS, which PM can't monitor. For others, you can try using the options page to select the area to monitor.
