### ISSUE TITLE
Hidden ASP problem

### ISSUE THREAD

**Issue by brunevsky** [max99x/pagemon-chrome-ext#348]
There is a problem with a site that I can't monitor. The site has a table that is hidden by a button. This table only appears when you press the button, and that's why I can't monitor it with the Page Monitor app. Could you please help me? 
The site is: https://www11.epm.com.co/ComprasMayores/contratacion.aspx
You have to click at the "CONSULTAR" button.

**Comment by max99x** [comment]
The content is only returned in response to a POST request. POST requests are intended to change state on the server and therefore should not be replayed. The site is arguably wrong in using POST for what appears to be a search. Regardless, Page Monitor is intentionally forbidden from doing POST requests.

**Comment by brunevsky** [comment]
Thank you max99x. But what can I do in this case? Is there any solution? Maybe a code or something that I can use to access this table by URL?
I'm lay with ASP, so I don't know exactly what is possible.

**Comment by max99x** [comment]
I don't think there's an easy way to do it. This uses ASP's heavyweight form management system which can't really be accessed by a predictable GET URL as afar as I know.

**Comment by brunevsky** [comment]
Ok, thank you very much for your help.
