### ISSUE TITLE
web.whatsapp.com

### ISSUE THREAD

**Issue by acidiusgreen** [max99x/pagemon-chrome-ext#349]
I've been trying all day but I cant get page monitor to work on whatsapp web. What I'm basically trying to do is that I'm trying to get a notification when a contact comes online on whatsapp web.

When a person comes online on whatsapp web an "online" appears under the contacts name. I found the div and the exact line of code is : 

span class="emojitext ellipsify" title="online" data-reactid="example contact">online</span

Tried with both selecter and regex but cant get it to work

**Comment by max99x** [comment]
If there's a public URL I can check (not being a user of whatsapp), I might be able to debug it, but chances are that it's set dynamically via JavaScript, which Page Monitor won't catch.

**Comment by acidiusgreen** [comment]
I think you'r probably right. Thanks for the fast response thought. I guess I'll have to try something else.
