### ISSUE TITLE
OWA chat support

### ISSUE THREAD

**Issue by zebrazoly** [max99x/pagemon-chrome-ext#351]
I use Outlook Web App everyday. One of its most annoying feature is that chat windows only pop up once (at the first message), then stay "silent" (no notifications).

I tried the Page Monitor on the main window, and it worked when I got new mail, but when it was set on a chat window, the changes weren't noticed.

Is there a way to make it work for the chat as well?

**Comment by max99x** [comment]
Unfortunately Page Monitor does not support pages that are updated dynamically at runtime using JavaScript. Try one of the page refresh extensions.

**Comment by zebrazoly** [comment]
Thanks, I will!
