### ISSUE TITLE
Everything is gone

### ISSUE THREAD

**Issue by Smilegrim** [max99x/pagemon-chrome-ext#352]
When opening up my computer after the weekend i noticed that there were no notifications and when checking Page Monitor Options, ALL the pages were gone. HELP! What should i do?

(I have checked the Web SQL - pages - pages  and there are nothing...)

**Comment by max99x** [comment]
If nothing shows up in the pages DB, the outlook is pretty grim. As a last resort, you could try taking the actual DB file and trying it on a different Chrome install or in an SQLite viewer. Find your [Chrome user data folder](http://www.chromium.org/user-experience/user-data-directory), and within it go to databases/chrome-extension_pemhgklkefakciniebenbfclihhmmfcd_0. There should be one file there, which is the database.
