### ISSUE TITLE
How can i see just what changed if there've been many checks since change was discovered??

### ISSUE THREAD

**Issue by domino66** [max99x/pagemon-chrome-ext#354]
I must be missing something because this issue seems too straight-forward...I have the extension set to check a URL every hour.  Today I came back from work and noticed the notification-icon over the extension icon, indicating a change.  So I went to the URL (a simple directory of files). But how can I tell what's different?  The extension's documentation seems to suggest it'll show you changes in highlighted color...but I see nothing highlighted.

But if I'm reading the extension's documentation correctly, it'll only show you changes it finds SINCE the last scan? Does that mean that if it finds a new change during its scheduled 4pm scan, but you're not home and it performs its automated 5pm, 6pm, 7pm scans, it'll no longer show you (via highlighting) what it found at 4pm??  What am I missing?

**Comment by max99x** [comment]
The checks only run until the first difference is observed, and the previous snapshot is used when diffing (against the current live content). In your example, the check would run every hour until 4PM, then stop until you check the page. When you do check the page, if you go to the diff page, the diff will be between whatever the content was when you last opened it (equivalent to the 3PM check) and the current content (at the time when you are checking it).
