### ISSUE TITLE
Some thoughts

### ISSUE THREAD

**Issue by onlyqmqy2** [max99x/pagemon-chrome-ext#357]
Hello,max99x

I'm a big fan of this plugin.

Many years ago,I have first  came into contact into this kind of web page monitor tools,it made me so surprised!At first,I use PM to monitor many pages that doesn't support rss.
In fact,I have to say,it's the most easy to use monitor like tools that I have ever seemd!
Do you know how popular did this plugin are in China?There're about 240,000 searching results in google with chinese,many website and computer magazine introduced PM.
Even I found some people use your source code to pack it up to another plugin with different name(without saying any of PageMonitor).I was so angry and I download its plugin and unpack、contrast the code,then I put this analysis to his weibo(a platform like twitter in China) which made him deleted his plugin.

However,after some months,I found that PM can't satisfy my desire about many features,and its instability(always crashing or data dropping) also made me feel annoying, so I have to choose the other solution....After few years,I have used many monitor like tools like "feed43"、"Yahoo pipe"、"page2rss" and so on.None of this in usability is better than PM.

I was so sad to see this plugin was in "maintenance mode".I was thinking,why you didn't charge a lot or to make this plugin became more powerful?Or made PM became a online services?You know,for the people who don't know how to pragram,PM just like the magic.

I don't know what's going on for you to quit developing new features,but I want you know that,I love this plugin,and I want to pay suitable for this project(time or money) even though I'm not rich.And I believed that many users would love to pay for your plugin just like me.

Hope you can do better.

A loyal user for Page Monitor.

**Comment by max99x** [comment]
Thanks for your kind words. It's great to hear that you like the extension and that it's popular in China. I wrote PM originally for my own use, and never intended to develop it as a paid product. However, I'm exploring some options that may allow Page Monitor to integrate with a more powerful third party monitoring service, so keep your eyes peeled for that.

On a side note, regarding the case of someone repackaging Page Monitor: while I appreciate your intent, I do want to highlight that PM is free, open-source software with a fully permissive MIT license. It is totally Ok with me if people reuse the code, with or without modifications for their own products. Ideally they should include the license text or attribution, but I don't mind either way.

**Comment by onlyqmqy2** [comment]
I'm so glad to see that.
Wish you can do better:)
