### ISSUE TITLE
Way to see the DATE a page was last changed?

### ISSUE THREAD

**Issue by domino66** [max99x/pagemon-chrome-ext#359]
In the MONITORED PAGES page, I have all of the pages I'm monitoring sorted by 'most recently updated'...but is there a way to see just WHEN each was updated? As it is, I'm kind of taking the extension's word for it when it orders the pages, but I want to know just WHEN each was last updated. Not too hard a request, so wondering if that's possible with this extension.

**Comment by max99x** [comment]
PM pages are sorted by the order in which they were added to the monitoring list. If you care about particular update times, on the options page, that time is the time listed under "Last Check:" for updated pages.
