### ISSUE TITLE
I lost history of the monitored pages due to the hard drive change.

### ISSUE THREAD

**Issue by JeanBonbeur** [max99x/pagemon-chrome-ext#363]
Hi,

I have access at my data on the old HDD. I can access at some's directory or files if de PM stock this info in one file.

I try to search this info on this site (but without search function, it's too hard, and more difficult, in english). Response in French are very Welcome :)

S'il vous plait, aidez moi !

Thanx a lot for your attention.

**Comment by max99x** [comment]
Go to the [Chrome user data folder](https://www.chromium.org/user-experience/user-data-directory). Under `databases/chrome-extension_pemhgklkefakciniebenbfclihhmmfcd_0` you'll find a single file with a numeric name (mine is called `53`). That's the page database, and copying it to the same path on your new system while Chrome is closed should restore the pages list.
